ListenPort = 8000
ListenAddr = "0.0.0.0"

# Database Configuration for "test"
[[databases]]
name = "test"
ssl = false
shouldPool = false
authMethod = "md5"

[[databases.clusters]]
name = "postgres"
host = "postgres1"
port = 5432
user = "root"
passwordEnv = "PG_PASSWORD_1"

[[databases.clusters]]
name = "postgres"
host = "postgres2"
port = 5433
user = "postgres"
passwordEnv = "PG_PASSWORD_2"

[[databases.clusters]]
name = "postgres"
host = "postgres3"
port = 5434
user = "postgres"
passwordEnv = "PG_PASSWORD_3"

[databases.poolSettings]
maxOpenConns = 10
maxConnLifetime = 900
