ListenPort = 8000
ListenAddr = "localhost"

# Database Configuration for "test"
[[databases]]
name = "test"
ssl = false
shouldPool = false
authMethod = "md5"

[[databases.clusters]]
name = "postgres"
host = "localhost"
port = 5432
user = "root"
passwordEnv = "PG_PASSWORD_1"

[databases.poolSettings]
maxOpenConns = 10
maxConnLifetime = 900
