ListenPort = 8000
ListenAddr = "localhost"

# Database Configuration for "test"
[[databases]]
name = "lyfe"
ssl = false
shouldPool = false
authMethod = "md5"

[[databases.clusters]]
name = "lyfe"
host = "main-postgres.dlaw"
port = 5432
user = "postgres"
passwordEnv = "PG_PASSWORD"

[databases.poolSettings]
maxOpenConns = 10
maxConnLifetime = 900
